#!/bin/bash

# exit on error
set -e

# famous-cli command to build the project, BROKEN and DEPRECATED, do not execute
famous build -m -o focus/www/
# remove the simlink to the original project
rm focus/www/original_project
# overwrite a predefined script to the index.html generated by the build tool
cp indexScript.html focus/www/index.html
cd focus
# build ios app for quicker deployment in xcode
cordova build ios
