//this script is placed in the script tag generated by the famous build whenever the app is build with cordova

document.addEventListener("deviceready", _startApp, false);

function _startApp() {
    console.log('starting famous');
    _famous();
    _accessFileSystem();
}

function _famous() {
    require(["app/main/index.js"]);
}

function _accessFileSystem() {
    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, _gotFileSystem, _fail);
}

function _gotFileSystem(fileSystem) {
    fileSystem.root.getFile("focusData.json", {create: true, exclusive: false}, _gotFileEntry, _fail);
}

function _gotFileEntry(fileEntry) {
    fileEntry.createWriter(_gotWriter, _fail);
    fileEntry.file        (_gotReader, _fail);
}

function _gotReader(file) {
    window._FileReader = new FileReader();
    window._FileReader.onloadend = function(evt) {
        console.log("read as text");
        console.log(evt.target.result);
        alert('read from disk');
    }

    window.FileReader = {
        read: function() {
            return window._FileReader.readAsText(file);
        }
    }

    // window.FileReader.read();
}

function _createWriter(writer) {
    writer.onwriteend = function(evt) {
        console.log("written to disk");
        alert('wrote to disk');
    };
    window.FileWriter = writer;
    window.FileWriter.write('Hello World');
    window.FileReader.read();
    // window.FileWriter.write(writeString);
}

function _fail(evt) {
    alert('error' + evt.target.error.code);
    console.log('error');
    console.log(evt.target.error.code);
}