
var tasks = [
  { text: 'make an app', page: 'FOCUS'},
  { text: 'be awesome', page: 'FOCUS'},
  { text: 'moonlight as catwoman', page: 'FOCUS'},
  { text: 'eat lunch', page: 'TODAY'},
  { text: 'find phone', page: 'TODAY'},
  { text: 'be awesome', page: 'TODAY'},
  { text: 'make app, heeeere', page: 'TODAY'},
  { text: 'eat lunch', page: 'TODAY'},
  { text: 'eat dinner', page: 'LATER'},
  { text: 'eat dinner', page: 'LATER'},
  { text: 'eat dinner', page: 'LATER'},
  { text: 'eat dinner', page: 'LATER'},
  { text: 'eat dinner', page: 'LATER'},
  { text: 'eat dinner', page: 'LATER'},
  { text: 'eat dinner', page: 'LATER'},
  { text: 'eat lunch', page: 'TODAY'},
  { text: 'eat dinner', page: 'TODAY'},
  { text: 'eat lunch', page: 'TODAY'},
  { text: 'eat dinner', page: 'NEVER'},
  { text: 'eat lunch', page: 'NEVER'},
  { text: 'eat dinner', page: 'NEVER'},
  // { text: 'make an app', page: 'FOCUS'},
  // { text: 'eat lunch', page: 'TODAY'},
  // { text: 'be awesome', page: 'FOCUS'},
  // { text: 'eat dinner', page: 'TODAY'},
  // { text: 'eat lunch', page: 'TODAY'},
  // { text: 'be awesome', page: 'FOCUS'},
  // { text: 'eat dinner', page: 'TODAY'},
  // { text: 'eat lunch', page: 'TODAY'},
  // { text: 'be awesome', page: 'FOCUS'},
  // { text: 'eat dinner', page: 'TODAY'},
  // { text: 'make an app', page: 'FOCUS'},
  // { text: 'eat lunch', page: 'TODAY'},
  // { text: 'be awesome', page: 'FOCUS'},
  // { text: 'eat dinner', page: 'TODAY'},
  // { text: 'eat lunch', page: 'TODAY'},
  // { text: 'be awesome', page: 'FOCUS'},
  // { text: 'eat dinner', page: 'TODAY'},
  // { text: 'eat lunch', page: 'TODAY'},
  // { text: 'be awesome', page: 'FOCUS'},
  { text: 'finish work', page: 'TODAY'}

];


module.exports = tasks;
